version: 0.2

env:
  shell: bash
  secrets-manager:
    GIVE_CI_USERNAME: give-ci-dev-secrets:GIVE_CI_USERNAME
    GIVE_CI_PASSWORD: give-ci-dev-secrets:GIVE_CI_PASSWORD
phases:
  install:
    commands:
      # Install CF CLI
      - pip install -r tests/requirements.txt
      - curl -v -L -o cf-cli_amd64.deb 'https://cli.run.pivotal.io/stable?release=debian64&source=github'
      - dpkg -i cf-cli_amd64.deb
      - cf -v
  post_build:
    commands:
      # Login to cloud.gov
      - cf login -a https://api.fr.cloud.gov -u $GIVE_CI_USERNAME -p $GIVE_CI_PASSWORD
      # Push app to cloud.gov and create a random route to avoid collision, but don't start it yet
      - cf push --vars-file vars.dev.yml
      # Setup services and routes for kong
      - ./post-deployment.sh
